### ISSUE TITLE
/hls/api/pull?streamPath为空时m7s会panic  runtime error: invalid memory address or nil pointer dereference，

### ISSUE THREAD

**Issue by fanshuangstrive** [Monibuca/engine#97]
例如请求http://127.0.0.1:8080/hls/api/pull?streamPath

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb218ee]

goroutine 117 [running]:
m7s.live/engine/v4.(*IO).IsClosed(...)
	/root/go/pkg/mod/m7s.live/engine/v4@v4.14.6-0.20231215101010-5e3008f00beb/io.go:55
m7s.live/engine/v4.(*IO).close(0xc0009aa380, {0xc000652500, 0x1, 0x1})
	/root/go/pkg/mod/m7s.live/engine/v4@v4.14.6-0.20231215101010-5e3008f00beb/io.go:109 +0x2e
m7s.live/engine/v4.(*IO).Stop(...)
	/root/go/pkg/mod/m7s.live/engine/v4@v4.14.6-0.20231215101010-5e3008f00beb/io.go:125
m7s.live/plugin/hls/v4.(*HLSPuller).Disconnect(0xc0009aa380)
	/root/go/pkg/mod/m7s.live/plugin/hls/v4@v4.3.8-0.20231213072004-7ec5ce26b101/pull.go:305 +0xcb
m7s.live/engine/v4.(*Puller).startPull.func1()
	/root/go/pkg/mod/m7s.live/engine/v4@v4.14.6-0.20231215101010-5e3008f00beb/puller.go:65 +0x67
m7s.live/engine/v4.(*Puller).startPull(0xc0009aa478, {0x25b9ee0?, 0xc0009aa380})
	/root/go/pkg/mod/m7s.live/engine/v4@v4.14.6-0.20231215101010-5e3008f00beb/puller.go:89 +0xd10
created by m7s.live/engine/v4.(*Plugin).Pull in goroutine 114
	/root/go/pkg/mod/m7s.live/engine/v4@v4.14.6-0.20231215101010-5e3008f00beb/plugin.go:281 +0x4da

**Comment by langhuihui** [comment]
这个不能为空

**Comment by fanshuangstrive** [comment]
> 这个不能为空

不能为空，也不用导致进程panic吧

**Comment by langhuihui** [comment]
你说的对，这里需要判断一下
